spark:
    app_name: "FlightDataETL"
    shuffle_partitions: 200
    driver_memory: "8g"
    local_ip: "127.0.0.1"
    log_level: "FATAL"
    jars_packages:
        - "org.apache.hadoop:hadoop-aws:3.4.2"
        - "com.amazonaws:aws-java-sdk-bundle:1.12.262"
    hadoop_conf:
        fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"


aws:
    region: "ap-southeast-1"
    s3:
        data-lake-bucket: "rwc-ml-datasets"
        data-warehouse-bucket: "rwc-data-warehouse"


logging:
    path: "/notebooks/ML/Flight Delay Prediction Project/logs/pipeline.log"
    level: "WARNING"