rootLogger.level = warn
rootLogger.appenderRef.file.ref = FileAppender

appender.file.type = File
appender.file.name = FileAppender
appender.file.fileName = /notebooks/ML/Flight Delay Prediction Project/logs/spark.log
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n